---
title: "lab4"
author: "Britt Bovbjerg"
date: "3/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data Cleaning: 
```{r}
library(readxl)
library(dplyr)
library(tidyverse)

defense <- read_excel("cyclonesFootball2019.xlsx", sheet="Defensive")
str(defense)

offensive <-read_excel("cyclonesFootball2019.xlsx", sheet="Offensive")

biography <-read_excel("cyclonesFootball2019.xlsx", sheet="Biography")

cols.num <- c("Tackles_Solo","Tackles_ASST", "Tackles_TFL","Tackles_Sack", "Turnover_FF","Turnover_FR","Turnover_INT", "Pass_QBH", "Pass_PB")

defense[cols.num] <- sapply(defense[cols.num],as.numeric)

defClean <- defense

defClean$Name <- as.factor(defClean$Name)

defClean$Opponent_Opponent <-as.factor(defClean$Opponent_Opponent)
            
str(defClean)


cols.num1 <- c("Rushing_ATT","Rushing_YDS", "Rushing_TD","Receiving_REC", "Receiving_YDS","Receiving_TD","Passing_CMP-ATT", "Passing_YDS", "Passing_TD", "Passing_INT")
offensive[cols.num1] <- sapply(offensive[cols.num1],as.numeric)

offClean <- offensive

offClean$Name <- as.factor(offClean$Name)

offClean$Opponent_Opponent <- as.factor(offClean$Opponent_Opponent)

str(offClean)

bioClean <- biography
bioClean$Name <- as.factor(bioClean$Name)
bioClean$Weight <- as.numeric(bioClean$Weight)

bioClean <- bioClean %>% 
  separate (col = Height, into= c("Feet", "Inches"),sep='-') %>%
  mutate_at(.vars = vars(Feet, Inches),
            .fun = funs(as.numeric))
  


View(bioClean)
str(bioClean)

```

Part 2
1)
```{r}
defClean %>% pivot_longer(Tackles_Solo:Pass_PB,
    names_to= 'Statistic')
```
2)
```{r}
ggplot(defclean, aes(value)) + geom_histogram() + facet_wrap(~Statistics)
```

It looks like tackles_Sacks, Turnover_FF, Turnover_FR and Turnover_INT are pretty rare.

3)
```{r}
defClean %>% pivot_wider %>%(names_from ='Name', values_from = 'Opponent_Opponent') +
  ggplot(defClean, aes(x= Tackles_Solo %in% 'Kansas City', y= Tackles_Solo %in% 'West Virginia')) + geom_point()
```

Part 3
1)
```{r}
bioClean <- bioClean  %>% separate(col = Hometown, into = c('Town','State'), sep = ',')

print(bioClean)
```

2)
```{r}
bioClean %>% ggplot(aes(State)) + geom_bar()
```

Part 3

1)
```{r}
offBioClean <- left_join(bioClean, offClean, id = 'Name')

offBioClean %>% ggplot(aes(State)) + geom_bar()
```

2)
```{r}
offBioClean %>% ggplot(aes(x= Receiving_YDS, y = Weight)) + geom_point() + facet_wrap(~Opponent_Opponent)
```
It really doesn't look like there's much of a relationship between weight and recieving yards. There's way too many other factors you would need to look at to make this data mean anything.

3)
```{r}
offBioClean %>% pivot_longer(Rushing_ATT:Passing_INT, names_to = 'Statistic') %>% ggplot(aes(x = Statistic, y = Position)) + geom_point() + facet_wrap(~Opponent_Opponent)
```

4)

